{{- if and .Values.prometheus.enabled .Values.prometheus.additionalPodMonitors }}
apiVersion: v1
kind: List
items:
{{- range .Values.prometheus.additionalPodMonitors }}
  - apiVersion: {{ printf "%s/v1" ($.Values.prometheusOperator.crdApiGroup | default "monitoring.coreos.com") }}
    kind: PodMonitor
    metadata:
      name: {{ .name }}
      labels:
        app: {{ template "prometheus-operator.name" $ }}-prometheus
{{ include "prometheus-operator.labels" $ | indent 8 }}
        {{- if .additionalLabels }}
{{ toYaml .additionalLabels | indent 8 }}
        {{- end }}
    spec:
      podMetricsEndpoints:
{{ toYaml .endpoints | indent 8 }}
    {{- if .jobLabel }}
      jobLabel: {{ .jobLabel }}
    {{- end }}
    {{- if .namespaceSelector }}
      namespaceSelector:
{{ toYaml .namespaceSelector | indent 8 }}
    {{- end }}
      selector:
{{ toYaml .selector | indent 8 }}
    {{- if .targetLabels }}
      targetLabels:
{{ toYaml .targetLabels | indent 8 }}
    {{- end }}
{{- end }}
{{- end }}
